### PR TITLE
Move abstract tests

### PR DESCRIPTION
**Pull request by enumag**
Needed for https://github.com/amphp/file/pull/43

### CODE REVIEW

**Comment by enumag** [comment]
Note: I'll also need a new release of amphp/sync after this is merged in order to continue my work in amphp/file.

**Comment by kelunik** [comment]
I'm not a fan of making tests part of the public API, especially as PHPUnit releases many more major versions as we do in our packages.

A work around is - - prefer-source combined with an autoload-dev rule.

**Comment by enumag** [comment]
I really dislike that workaround to be honest. 😅

**Comment by enumag** [comment]
I really dislike that workaround to be honest. 😅  But if that's what you guys prefer... @trowski ?

**Comment by enumag** [comment]
The workaround was used instead so this is now obsolete. Closing.

**Pull request closed without merging**
